name: Build ALL 

on:
  workflow_dispatch:

jobs:
  build:
    name: Build all keyboard
    runs-on: ubuntu-latest

    steps:
    - name: Get source
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Tools
      run: |
        sudo apt-get update
        sudo apt-get -y install python3-pip git python3
        sudo pip3 install --upgrade pip
        sudo python3 -m pip install --user qmk
        sudo echo 'PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc && source $HOME/.bashrc

    - name: Make
      run: |
        make cx60:default
    - name: Upload Artifact Files
      uses: actions/upload-artifact@v2
      with:
        name: Keyboard_Firmware
        path: |
#          /home/runner/work/qmk_firmware/qmk_firmware/.build/*.zip
          /home/runner/work/qmk_firmware/qmk_firmware/.build/*.hex