name: Make

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build keyboard
    runs-on: ubuntu-latest

    steps:
    - name: Get source
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Tools
      run: |
        sudo apt-get update
        sudo apt-get -y install git python python3 python3-pip
        cd util
        sh qmk_install.sh


    - name: Make
      run: |
        cd ..
        make cx60:default

    - name: Upload Artifact Files
      uses: actions/upload-artifact@v2
      with: 
        name: Keyboard_Firmware
        path: |
          /home/runner/work/qmk_firmware/qmk_firmware/.build/*.hex