name: Make

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    paths:
    - 'builddefs/**'
    - 'quantum/**'
    - 'platforms/**'
    - 'tmk_core/**'
    - 'tests/**'
    - '*.mk'
    - 'Makefile'
    - '.github/workflows/unit_test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    container: qmkfm/base_container

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: make cx60:default


    - name: Upload Artifact Files
      uses: actions/upload-artifact@v2
      with: 
        name: Keyboard_Firmware
        path: |
#          /home/runner/work/qmk_firmware/qmk_firmware/.build/*.zip
          /home/runner/work/qmk_firmware/qmk_firmware/.build/*.hex